# Generated by Django 5.1.3 on 2024-12-11 21:37

import orden.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='orderID',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orden',
            name='status',
            field=models.CharField(choices=[(orden.models.OrdenStatus['CREATED'], 'CREATED'), (orden.models.OrdenStatus['PAYED'], 'PAYED'), (orden.models.OrdenStatus['COMPLETED'], 'COMPLETED'), (orden.models.OrdenStatus['CANCELED'], 'CANCELED')], default=orden.models.OrdenStatus['CREATED'], max_length=40),
        ),
    ]
