# Generated by Django 5.1.3 on 2024-12-09 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartproduct'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cartproduct',
            table='cart_product',
        ),
    ]
